repoServer:
  pv:
    name: argocd-repo-server-pv
    storage: 5Gi
    accessMode: ReadWriteOnce
    reclaimPolicy: Retain
    storageClass: standard
    hostPath: /tmp/argocd-repo-server
  pvc:
    name: argocd-repo-server-pvc
    storage: 5Gi
    accessMode: ReadWriteOnce
    storageClass: standard
    volumeName: argocd-repo-server-pv

redis:
  pv:
    name: redis-pv
    storage: 1Gi
    accessMode: ReadWriteOnce
    reclaimPolicy: Retain
    storageClass: standard
    hostPath: /mnt/data/redis
  pvc:
    name: redis-pvc
    storage: 1Gi
    accessMode: ReadWriteOnce
    storageClass: standard
    namespace: argocd
