apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.pv.name }}
spec:
  capacity:
    storage: {{ .Values.redis.pv.storage }}
  accessModes:
    - {{ .Values.redis.pv.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.redis.pv.reclaimPolicy }}
  storageClassName: {{ .Values.redis.pv.storageClass }}
  hostPath:
    path: {{ .Values.redis.pv.hostPath }}
    type: DirectoryOrCreate
