apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.repoServer.pvc.name }}
spec:
  accessModes:
    - {{ .Values.repoServer.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.repoServer.pvc.storage }}
  storageClassName: {{ .Values.repoServer.pvc.storageClass }}
  volumeName: {{ .Values.repoServer.pvc.volumeName }}
